name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    uses: stylelint/.github/.github/workflows/call-lint.yml@38848ee8badc3888f246692cc371d519616d74e2 # 0.9.0
    permissions:
      contents: read

  test:
    uses: stylelint/.github/.github/workflows/call-test.yml@38848ee8badc3888f246692cc371d519616d74e2 # 0.9.0
    permissions:
      contents: read

  dependency-review:
    if: github.event_name == 'pull_request'
    uses: stylelint/.github/.github/workflows/call-dependency-review.yml@38848ee8badc3888f246692cc371d519616d74e2 # 0.9.0
    permissions:
      contents: read
