name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    uses: stylelint/.github/.github/workflows/call-lint.yml@ab7979355590956aa96d306dedfda6b2d42c4982 # 1.1.0
    permissions:
      contents: read

  test:
    uses: stylelint/.github/.github/workflows/call-test.yml@ab7979355590956aa96d306dedfda6b2d42c4982 # 1.1.0
    permissions:
      contents: read

  dependency-review:
    if: github.event_name == 'pull_request'
    uses: stylelint/.github/.github/workflows/call-dependency-review.yml@ab7979355590956aa96d306dedfda6b2d42c4982 # 1.1.0
    permissions:
      contents: read
